//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Experentia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comision
    {
        public Comision()
        {
            this.Grupo = new HashSet<Grupo>();
            this.Materia = new HashSet<Materia>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<Grupo> Grupo { get; set; }
        public virtual ICollection<Materia> Materia { get; set; }
    }
}
