//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Experentia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materia
    {
        public Materia()
        {
            this.Alumno = new HashSet<Alumno>();
            this.Coordinador = new HashSet<Coordinador>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<int> idComision { get; set; }
    
        public virtual Comision Comision { get; set; }
        public virtual ICollection<Alumno> Alumno { get; set; }
        public virtual ICollection<Coordinador> Coordinador { get; set; }
    }
}
